// This file was generated by Mendix Modeler 7.5.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package email.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the Email module
	public static void orderPlacedEmail(IContext context, main.proxies.Order _order, emailtemplate.proxies.EmailTemplate _emailTemplate, main.proxies.Customer _customer)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Order", _order == null ? null : _order.getMendixObject());
			params.put("EmailTemplate", _emailTemplate == null ? null : _emailTemplate.getMendixObject());
			params.put("Customer", _customer == null ? null : _customer.getMendixObject());
			Core.execute(context, "Email.OrderPlacedEmail", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void orderShippedEmail(IContext context, main.proxies.Order _order, main.proxies.Customer _customer)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Order", _order == null ? null : _order.getMendixObject());
			params.put("Customer", _customer == null ? null : _customer.getMendixObject());
			Core.execute(context, "Email.OrderShippedEmail", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}