// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package main.proxies;

public class OrderLine
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject orderLineMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Main.OrderLine";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Quanity("Quanity"),
		sellingPrice("sellingPrice"),
		lineValue("lineValue"),
		OrderLine_Stock("Main.OrderLine_Stock"),
		OrderLine_Order("Main.OrderLine_Order"),
		OrderLine_Product("Main.OrderLine_Product");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public OrderLine(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Main.OrderLine"));
	}

	protected OrderLine(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject orderLineMendixObject)
	{
		if (orderLineMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Main.OrderLine", orderLineMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Main.OrderLine");

		this.orderLineMendixObject = orderLineMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'OrderLine.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static main.proxies.OrderLine initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return main.proxies.OrderLine.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static main.proxies.OrderLine initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new main.proxies.OrderLine(context, mendixObject);
	}

	public static main.proxies.OrderLine load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return main.proxies.OrderLine.initialize(context, mendixObject);
	}

	public static java.util.List<main.proxies.OrderLine> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<main.proxies.OrderLine> result = new java.util.ArrayList<main.proxies.OrderLine>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Main.OrderLine" + xpathConstraint))
			result.add(main.proxies.OrderLine.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Quanity
	 */
	public final java.lang.Integer getQuanity()
	{
		return getQuanity(getContext());
	}

	/**
	 * @param context
	 * @return value of Quanity
	 */
	public final java.lang.Integer getQuanity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Quanity.toString());
	}

	/**
	 * Set value of Quanity
	 * @param quanity
	 */
	public final void setQuanity(java.lang.Integer quanity)
	{
		setQuanity(getContext(), quanity);
	}

	/**
	 * Set value of Quanity
	 * @param context
	 * @param quanity
	 */
	public final void setQuanity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer quanity)
	{
		getMendixObject().setValue(context, MemberNames.Quanity.toString(), quanity);
	}

	/**
	 * @return value of sellingPrice
	 */
	public final java.math.BigDecimal getsellingPrice()
	{
		return getsellingPrice(getContext());
	}

	/**
	 * @param context
	 * @return value of sellingPrice
	 */
	public final java.math.BigDecimal getsellingPrice(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.sellingPrice.toString());
	}

	/**
	 * Set value of sellingPrice
	 * @param sellingprice
	 */
	public final void setsellingPrice(java.math.BigDecimal sellingprice)
	{
		setsellingPrice(getContext(), sellingprice);
	}

	/**
	 * Set value of sellingPrice
	 * @param context
	 * @param sellingprice
	 */
	public final void setsellingPrice(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal sellingprice)
	{
		getMendixObject().setValue(context, MemberNames.sellingPrice.toString(), sellingprice);
	}

	/**
	 * @return value of lineValue
	 */
	public final java.math.BigDecimal getlineValue()
	{
		return getlineValue(getContext());
	}

	/**
	 * @param context
	 * @return value of lineValue
	 */
	public final java.math.BigDecimal getlineValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.lineValue.toString());
	}

	/**
	 * Set value of lineValue
	 * @param linevalue
	 */
	public final void setlineValue(java.math.BigDecimal linevalue)
	{
		setlineValue(getContext(), linevalue);
	}

	/**
	 * Set value of lineValue
	 * @param context
	 * @param linevalue
	 */
	public final void setlineValue(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal linevalue)
	{
		getMendixObject().setValue(context, MemberNames.lineValue.toString(), linevalue);
	}

	/**
	 * @return value of OrderLine_Stock
	 */
	public final main.proxies.Stock getOrderLine_Stock() throws com.mendix.core.CoreException
	{
		return getOrderLine_Stock(getContext());
	}

	/**
	 * @param context
	 * @return value of OrderLine_Stock
	 */
	public final main.proxies.Stock getOrderLine_Stock(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		main.proxies.Stock result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.OrderLine_Stock.toString());
		if (identifier != null)
			result = main.proxies.Stock.load(context, identifier);
		return result;
	}

	/**
	 * Set value of OrderLine_Stock
	 * @param orderline_stock
	 */
	public final void setOrderLine_Stock(main.proxies.Stock orderline_stock)
	{
		setOrderLine_Stock(getContext(), orderline_stock);
	}

	/**
	 * Set value of OrderLine_Stock
	 * @param context
	 * @param orderline_stock
	 */
	public final void setOrderLine_Stock(com.mendix.systemwideinterfaces.core.IContext context, main.proxies.Stock orderline_stock)
	{
		if (orderline_stock == null)
			getMendixObject().setValue(context, MemberNames.OrderLine_Stock.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.OrderLine_Stock.toString(), orderline_stock.getMendixObject().getId());
	}

	/**
	 * @return value of OrderLine_Order
	 */
	public final main.proxies.Order getOrderLine_Order() throws com.mendix.core.CoreException
	{
		return getOrderLine_Order(getContext());
	}

	/**
	 * @param context
	 * @return value of OrderLine_Order
	 */
	public final main.proxies.Order getOrderLine_Order(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		main.proxies.Order result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.OrderLine_Order.toString());
		if (identifier != null)
			result = main.proxies.Order.load(context, identifier);
		return result;
	}

	/**
	 * Set value of OrderLine_Order
	 * @param orderline_order
	 */
	public final void setOrderLine_Order(main.proxies.Order orderline_order)
	{
		setOrderLine_Order(getContext(), orderline_order);
	}

	/**
	 * Set value of OrderLine_Order
	 * @param context
	 * @param orderline_order
	 */
	public final void setOrderLine_Order(com.mendix.systemwideinterfaces.core.IContext context, main.proxies.Order orderline_order)
	{
		if (orderline_order == null)
			getMendixObject().setValue(context, MemberNames.OrderLine_Order.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.OrderLine_Order.toString(), orderline_order.getMendixObject().getId());
	}

	/**
	 * @return value of OrderLine_Product
	 */
	public final main.proxies.Product getOrderLine_Product() throws com.mendix.core.CoreException
	{
		return getOrderLine_Product(getContext());
	}

	/**
	 * @param context
	 * @return value of OrderLine_Product
	 */
	public final main.proxies.Product getOrderLine_Product(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		main.proxies.Product result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.OrderLine_Product.toString());
		if (identifier != null)
			result = main.proxies.Product.load(context, identifier);
		return result;
	}

	/**
	 * Set value of OrderLine_Product
	 * @param orderline_product
	 */
	public final void setOrderLine_Product(main.proxies.Product orderline_product)
	{
		setOrderLine_Product(getContext(), orderline_product);
	}

	/**
	 * Set value of OrderLine_Product
	 * @param context
	 * @param orderline_product
	 */
	public final void setOrderLine_Product(com.mendix.systemwideinterfaces.core.IContext context, main.proxies.Product orderline_product)
	{
		if (orderline_product == null)
			getMendixObject().setValue(context, MemberNames.OrderLine_Product.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.OrderLine_Product.toString(), orderline_product.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return orderLineMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final main.proxies.OrderLine that = (main.proxies.OrderLine) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Main.OrderLine";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
