// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package main.proxies;

public class Product extends system.proxies.Image
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Main.Product";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ItemName("ItemName"),
		ItemDescription("ItemDescription"),
		ItemNumber("ItemNumber"),
		Status("Status"),
		TotalStock("TotalStock"),
		PublicThumbnailPath("PublicThumbnailPath"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		Product_Order("Main.Product_Order");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Product(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Main.Product"));
	}

	protected Product(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject productMendixObject)
	{
		super(context, productMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("Main.Product", productMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Main.Product");
	}

	/**
	 * @deprecated Use 'Product.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static main.proxies.Product initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return main.proxies.Product.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static main.proxies.Product initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new main.proxies.Product(context, mendixObject);
	}

	public static main.proxies.Product load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return main.proxies.Product.initialize(context, mendixObject);
	}

	public static java.util.List<main.proxies.Product> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<main.proxies.Product> result = new java.util.ArrayList<main.proxies.Product>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Main.Product" + xpathConstraint))
			result.add(main.proxies.Product.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of ItemName
	 */
	public final java.lang.String getItemName()
	{
		return getItemName(getContext());
	}

	/**
	 * @param context
	 * @return value of ItemName
	 */
	public final java.lang.String getItemName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ItemName.toString());
	}

	/**
	 * Set value of ItemName
	 * @param itemname
	 */
	public final void setItemName(java.lang.String itemname)
	{
		setItemName(getContext(), itemname);
	}

	/**
	 * Set value of ItemName
	 * @param context
	 * @param itemname
	 */
	public final void setItemName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String itemname)
	{
		getMendixObject().setValue(context, MemberNames.ItemName.toString(), itemname);
	}

	/**
	 * @return value of ItemDescription
	 */
	public final java.lang.String getItemDescription()
	{
		return getItemDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of ItemDescription
	 */
	public final java.lang.String getItemDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ItemDescription.toString());
	}

	/**
	 * Set value of ItemDescription
	 * @param itemdescription
	 */
	public final void setItemDescription(java.lang.String itemdescription)
	{
		setItemDescription(getContext(), itemdescription);
	}

	/**
	 * Set value of ItemDescription
	 * @param context
	 * @param itemdescription
	 */
	public final void setItemDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String itemdescription)
	{
		getMendixObject().setValue(context, MemberNames.ItemDescription.toString(), itemdescription);
	}

	/**
	 * @return value of ItemNumber
	 */
	public final java.lang.Long getItemNumber()
	{
		return getItemNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of ItemNumber
	 */
	public final java.lang.Long getItemNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.ItemNumber.toString());
	}

	/**
	 * Set value of ItemNumber
	 * @param itemnumber
	 */
	public final void setItemNumber(java.lang.Long itemnumber)
	{
		setItemNumber(getContext(), itemnumber);
	}

	/**
	 * Set value of ItemNumber
	 * @param context
	 * @param itemnumber
	 */
	public final void setItemNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long itemnumber)
	{
		getMendixObject().setValue(context, MemberNames.ItemNumber.toString(), itemnumber);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final main.proxies.ProductStatus getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final main.proxies.ProductStatus getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Status.toString());
		if (obj == null)
			return null;

		return main.proxies.ProductStatus.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(main.proxies.ProductStatus status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, main.proxies.ProductStatus status)
	{
		if (status != null)
			getMendixObject().setValue(context, MemberNames.Status.toString(), status.toString());
		else
			getMendixObject().setValue(context, MemberNames.Status.toString(), null);
	}

	/**
	 * @return value of TotalStock
	 */
	public final java.lang.Integer getTotalStock()
	{
		return getTotalStock(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalStock
	 */
	public final java.lang.Integer getTotalStock(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.TotalStock.toString());
	}

	/**
	 * Set value of TotalStock
	 * @param totalstock
	 */
	public final void setTotalStock(java.lang.Integer totalstock)
	{
		setTotalStock(getContext(), totalstock);
	}

	/**
	 * Set value of TotalStock
	 * @param context
	 * @param totalstock
	 */
	public final void setTotalStock(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer totalstock)
	{
		getMendixObject().setValue(context, MemberNames.TotalStock.toString(), totalstock);
	}

	/**
	 * @return value of Product_Order
	 */
	public final main.proxies.Order getProduct_Order() throws com.mendix.core.CoreException
	{
		return getProduct_Order(getContext());
	}

	/**
	 * @param context
	 * @return value of Product_Order
	 */
	public final main.proxies.Order getProduct_Order(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		main.proxies.Order result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Product_Order.toString());
		if (identifier != null)
			result = main.proxies.Order.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Product_Order
	 * @param product_order
	 */
	public final void setProduct_Order(main.proxies.Order product_order)
	{
		setProduct_Order(getContext(), product_order);
	}

	/**
	 * Set value of Product_Order
	 * @param context
	 * @param product_order
	 */
	public final void setProduct_Order(com.mendix.systemwideinterfaces.core.IContext context, main.proxies.Order product_order)
	{
		if (product_order == null)
			getMendixObject().setValue(context, MemberNames.Product_Order.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Product_Order.toString(), product_order.getMendixObject().getId());
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final main.proxies.Product that = (main.proxies.Product) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Main.Product";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
