// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package main.proxies;

public class Stock
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject stockMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Main.Stock";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Quanity("Quanity"),
		Shipped("Shipped"),
		Stock_Product("Main.Stock_Product");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Stock(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Main.Stock"));
	}

	protected Stock(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject stockMendixObject)
	{
		if (stockMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Main.Stock", stockMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Main.Stock");

		this.stockMendixObject = stockMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Stock.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static main.proxies.Stock initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return main.proxies.Stock.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static main.proxies.Stock initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new main.proxies.Stock(context, mendixObject);
	}

	public static main.proxies.Stock load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return main.proxies.Stock.initialize(context, mendixObject);
	}

	public static java.util.List<main.proxies.Stock> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<main.proxies.Stock> result = new java.util.ArrayList<main.proxies.Stock>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Main.Stock" + xpathConstraint))
			result.add(main.proxies.Stock.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Quanity
	 */
	public final java.lang.Integer getQuanity()
	{
		return getQuanity(getContext());
	}

	/**
	 * @param context
	 * @return value of Quanity
	 */
	public final java.lang.Integer getQuanity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Quanity.toString());
	}

	/**
	 * Set value of Quanity
	 * @param quanity
	 */
	public final void setQuanity(java.lang.Integer quanity)
	{
		setQuanity(getContext(), quanity);
	}

	/**
	 * Set value of Quanity
	 * @param context
	 * @param quanity
	 */
	public final void setQuanity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer quanity)
	{
		getMendixObject().setValue(context, MemberNames.Quanity.toString(), quanity);
	}

	/**
	 * @return value of Shipped
	 */
	public final java.lang.Integer getShipped()
	{
		return getShipped(getContext());
	}

	/**
	 * @param context
	 * @return value of Shipped
	 */
	public final java.lang.Integer getShipped(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Shipped.toString());
	}

	/**
	 * Set value of Shipped
	 * @param shipped
	 */
	public final void setShipped(java.lang.Integer shipped)
	{
		setShipped(getContext(), shipped);
	}

	/**
	 * Set value of Shipped
	 * @param context
	 * @param shipped
	 */
	public final void setShipped(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer shipped)
	{
		getMendixObject().setValue(context, MemberNames.Shipped.toString(), shipped);
	}

	/**
	 * @return value of Stock_Product
	 */
	public final main.proxies.Product getStock_Product() throws com.mendix.core.CoreException
	{
		return getStock_Product(getContext());
	}

	/**
	 * @param context
	 * @return value of Stock_Product
	 */
	public final main.proxies.Product getStock_Product(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		main.proxies.Product result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Stock_Product.toString());
		if (identifier != null)
			result = main.proxies.Product.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Stock_Product
	 * @param stock_product
	 */
	public final void setStock_Product(main.proxies.Product stock_product)
	{
		setStock_Product(getContext(), stock_product);
	}

	/**
	 * Set value of Stock_Product
	 * @param context
	 * @param stock_product
	 */
	public final void setStock_Product(com.mendix.systemwideinterfaces.core.IContext context, main.proxies.Product stock_product)
	{
		if (stock_product == null)
			getMendixObject().setValue(context, MemberNames.Stock_Product.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Stock_Product.toString(), stock_product.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return stockMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final main.proxies.Stock that = (main.proxies.Stock) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Main.Stock";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
