// This file was generated by Mendix Modeler 7.5.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package cart.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the Cart module
	public static void addToCart(IContext context, main.proxies.Product _product)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Product", _product == null ? null : _product.getMendixObject());
			Core.execute(context, "Cart.AddToCart", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static main.proxies.Price calPrice(IContext context, main.proxies.Product _product)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Product", _product == null ? null : _product.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "Cart.CalPrice", params);
			return result == null ? null : main.proxies.Price.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static cart.proxies.ShoppingCart getorCreateCart(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "Cart.GetorCreateCart", params);
			return result == null ? null : cart.proxies.ShoppingCart.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void minusOne(IContext context, cart.proxies.ShoppingCartLine _shoppingCartLine, cart.proxies.ShoppingCart _shoppingCart)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("ShoppingCartLine", _shoppingCartLine == null ? null : _shoppingCartLine.getMendixObject());
			params.put("ShoppingCart", _shoppingCart == null ? null : _shoppingCart.getMendixObject());
			Core.execute(context, "Cart.MinusOne", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void placeOrder(IContext context, cart.proxies.ShoppingCart _shoppingCart)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("ShoppingCart", _shoppingCart == null ? null : _shoppingCart.getMendixObject());
			Core.execute(context, "Cart.PlaceOrder", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void plusOne(IContext context, cart.proxies.ShoppingCartLine _shoppingCartLine, cart.proxies.ShoppingCart _shoppingCart)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("ShoppingCartLine", _shoppingCartLine == null ? null : _shoppingCartLine.getMendixObject());
			params.put("ShoppingCart", _shoppingCart == null ? null : _shoppingCart.getMendixObject());
			Core.execute(context, "Cart.PlusOne", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void removeFromCart(IContext context, cart.proxies.ShoppingCart _shoppingCart, cart.proxies.ShoppingCartLine _shoppingCartLine)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("ShoppingCart", _shoppingCart == null ? null : _shoppingCart.getMendixObject());
			params.put("ShoppingCartLine", _shoppingCartLine == null ? null : _shoppingCartLine.getMendixObject());
			Core.execute(context, "Cart.RemoveFromCart", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void showShoppingCart(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "Cart.ShowShoppingCart", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}